repositories:
- name: frp-operator
  url: https://zufardhiyaulhaq.com/frp-operator/charts/releases/
- name: sealed-secrets
  url: https://bitnami.github.io/sealed-secrets
- name: jetstack
  url: https://charts.jetstack.io
- name: external-dns
  url: https://kubernetes-sigs.github.io/external-dns/
- name: argo
  url: https://argoproj.github.io/argo-helm
- name: vm
  url: https://victoriametrics.github.io/helm-charts/
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus-operator-crds
  namespace: observability-system
  version: 31.0.1
  chart: prometheus-community/prometheus-operator-crds

- name: sealed-secrets
  namespace: infrastructure
  version: 2.18.6
  chart: sealed-secrets/sealed-secrets
  values:
  - releases/infrastructure/sealed-secret.yaml

- name: cert-manager
  namespace: infrastructure
  version: v1.21.1
  chart: jetstack/cert-manager
  values:
  - releases/infrastructure/cert-manager.yaml

- name: external-dns
  namespace: infrastructure
  version: 1.21.1
  chart: external-dns/external-dns
  values:
  - releases/infrastructure/external-dns.yaml

- name: frp-operator
  namespace: infrastructure
  version: 1.8.0
  chart: frp-operator/frp-operator
  needs:
  - observability-system/prometheus-operator-crds
  values:
  - releases/infrastructure/frp-operator.yaml

- name: argocd
  namespace: argocd-system
  version: 10.4.1
  chart: argo/argo-cd
  values:
  - releases/argocd-system/argocd.yaml

- name: victoria-metrics
  namespace: observability-system
  version: 0.91.2
  chart: vm/victoria-metrics-k8s-stack
  values:
  - releases/observability-system/victoria-metrics.yaml
