apiVersion: install.istio.io/v1alpha3
kind: IstioOperator
metadata:
  name: istio-service-gateway
  namespace: istio-system
spec:
  hub: ghcr.io/resf/istio
  profile: empty
  components:
    ingressGateways:
    - enabled: true
      name: istio-service-gateway
      label:
        app: istio-service-gateway
      k8s:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: istio-service-gateway
                topologyKey: kubernetes.io/hostname
              weight: 100
        resources:
          requests:
            cpu: 32m
            memory: 32Mi
        priorityClassName: system-cluster-critical
        podDisruptionBudget:
          minAvailable: 1
        hpaSpec:
          maxReplicas: 2
          minReplicas: 1
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        overlays:
          - kind: Deployment
            name: istio-service-gateway
            patches:
              - path: spec.template.spec.containers.[name:istio-proxy].lifecycle
                value:
                  preStop:
                    exec:
                      command:
                        - /bin/sh
                        - -c
                        - sleep 10
        podAnnotations:
          proxy.istio.io/config: |
            terminationDrainDuration: 30s
        service:
          type: ClusterIP
          ports:
          - port: 80
            targetPort: 8080
            name: http2
