apiVersion: community.zufardhiyaulhaq.com/v1alpha1
kind: Weekly
metadata:
  name: golang-weekly-465
  namespace: community
spec:
  community:
  - golang
  spec:
    name: Golang Weekly 465
    date: 06/25/2023
    imageUrl: https://trungtq.com/wp-content/uploads/2018/12/GO-3.png
    tags:
    - weekly
    - golang
    articles:
    - title: Initializing Large Static Maps in Go
      url: https://golangweekly.com/link/141236/web
      type: News
    - title: 'math/rand/v2: A New API for math/rand?'
      url: https://golangweekly.com/link/141238/web
      type: News
    - title: 'Revolutionize User Engagement with a Notification Inbox: Go SDK'
      url: https://golangweekly.com/link/141235/web
      type: News
    - title: Focus on the Happy Path with the 'Step Functions' Pattern
      url: https://golangweekly.com/link/141239/web
      type: News
    - title: 'Comparing Stacks for Building REST APIs: Go vs the World'
      url: https://golangweekly.com/link/141252/web
      type: News
    - title: kubectl Cheat Sheet
      url: https://golangweekly.com/link/141255/web
      type: News
    - title: 'Dasel: Query and Update Data Structures from the Command Line'
      url: https://golangweekly.com/link/141259/web
      type: News
    - title: 'Pie 2.7: A Utility Library for Dealing with Slices'
      url: https://golangweekly.com/link/141260/web
      type: News
    - title: 'GoAWK: An AWK Interpreter Written in Go'
      url: https://golangweekly.com/link/141261/web
      type: News
    - title: Tuple – The Fastest Way to Onboard New Devs
      url: https://golangweekly.com/link/141264/web
      type: News
    - title: 'Dbmate: A Lightweight, Framework-Agnostic Database Migration Tool'
      url: https://golangweekly.com/link/141265/web
      type: News
    - title: 'Anywherelan: A Mesh VPN System Built in Go'
      url: https://golangweekly.com/link/141266/web
      type: News
