apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fastgateway-zufardhiyaulhaq-com-cert
  namespace: istio-system
spec:
  secretName: fastgateway-zufardhiyaulhaq-com-cert
  issuerRef:
    name: zufardhiyaulhaq-com-cluster-issuer
    kind: ClusterIssuer
  commonName: "fastgateway.zufardhiyaulhaq.com"
  dnsNames:
  - "fastgateway.zufardhiyaulhaq.com"
