# kubernetes-sigs external-dns (migrated from bitnami). registry.k8s.io images.
provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns
        key: cloudflare_api_token

sources:
  - crd

policy: create-only
interval: "1m"
logLevel: debug

resources:
  requests:
    cpu: 16m
    memory: 16Mi
