operator:
  # image of frp-operator
  image: "ghcr.io/zufardhiyaulhaq/frp-operator"
  # tag of frp-operator image
  tag: "v0.10.0"
  # number of replica for deployment
  replica: 1

resources:
  requests:
    cpu: 16m
    memory: 64Mi

metrics:
  serviceMonitor:
    enabled: true
    interval: 30s
