apiVersion: install.istio.io/v1alpha3
kind: IstioOperator
metadata:
  name: control-plane
  namespace: istio-system
spec:
  hub: registry.istio.io/release
  profile: minimal
  components:
    pilot:
      enabled: true
      k8s:
        env:
          - name: METRIC_ROTATION_INTERVAL
            value: "2m0s"
          - name: METRIC_GRACEFUL_DELETION_INTERVAL
            value: "5m0s"
          - name: PILOT_DEBOUNCE_AFTER
            value: "500ms"
          - name: PILOT_DEBOUNCE_MAX
            value: "2s"
          - name: PILOT_ENABLE_EDS_DEBOUNCE
            value: "true"
          - name: ENABLE_NATIVE_SIDECARS
            value: "true"
          - name: PILOT_ENABLE_IP_AUTOALLOCATE
            value: "true"
        serviceAnnotations:
          service.kubernetes.io/topology-aware-hints: auto
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: istiod
                    istio: pilot
                topologyKey: kubernetes.io/hostname
              weight: 100
        resources:
          requests:
            cpu: 70m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        priorityClassName: system-cluster-critical
        podDisruptionBudget:
          minAvailable: 1
        hpaSpec:
          maxReplicas: 2
          minReplicas: 1
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
  meshConfig:
    tlsDefaults:
      ecdhCurves:
      - X25519MLKEM768
      - X25519
      - P-256
    tcpKeepalive:
      time: 60s
      probes: 3
      interval: 60s
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    accessLogFormat: |
      {
        "protocol": "%PROTOCOL%",
        "duration": "%DURATION%",
        "route_name": "%ROUTE_NAME%",
        "user_agent": "%REQ(USER-AGENT)%",
        "response_code": "%RESPONSE_CODE%",
        "response_flags": "%RESPONSE_FLAGS%",
        "start_time": "%START_TIME%",
        "method": "%REQ(:METHOD)%",
        "request_id": "%REQ(X-REQUEST-ID)%",
        "connection_id": "%CONNECTION_ID%",
        "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
        "x_forwarded_host": "%REQ(X-FORWARDED-HOST)%",
        "client_ip": "%REQ(True-Client-Ip)%",
        "requested_server_name": "%REQUESTED_SERVER_NAME%",
        "bytes_received": "%BYTES_RECEIVED%",
        "bytes_sent": "%BYTES_SENT%",
        "authority": "%REQ(:AUTHORITY)%",
        "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
        "response_code_details": "%RESPONSE_CODE_DETAILS%",
        "connection_termination_details": "%CONNECTION_TERMINATION_DETAILS%",
        "grpc_status_code": "%GRPC_STATUS_NUMBER%",
        "downstream_tls_version": "%DOWNSTREAM_TLS_VERSION%",
        "downstream_tls_session_id": "%DOWNSTREAM_TLS_SESSION_ID%",
        "downstream_peer_certificate_validity_start": "%DOWNSTREAM_PEER_CERT_V_START%",
        "downstream_peer_certificate_validity_end": "%DOWNSTREAM_PEER_CERT_V_END%",
        "downstream_peer_uri_san": "%DOWNSTREAM_PEER_URI_SAN%",
        "downstream_peer_issuer": "%DOWNSTREAM_PEER_ISSUER%",
        "downstream_peer_subject": "%DOWNSTREAM_PEER_SUBJECT%",
        "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
        "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
        "downstream_remote_address_without_port": "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%",
        "upstream_service_time": "%RESP(x-envoy-upstream-service-time)%",
        "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
        "upstream_remote_address": "%UPSTREAM_REMOTE_ADDRESS%",
        "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
        "upstream_protocol": "%UPSTREAM_PROTOCOL%",
        "upstream_peer_subject": "%UPSTREAM_PEER_SUBJECT%",
        "upstream_peer_issuer": "%UPSTREAM_PEER_ISSUER%",
        "upstream_tls_version": "%UPSTREAM_TLS_VERSION%",
        "upstream_peer_certificate_validity_end": "%UPSTREAM_PEER_CERT_V_END%",
        "upstream_host": "%UPSTREAM_HOST%",
        "upstream_cluster": "%UPSTREAM_CLUSTER%",
        "upstream_request_attempt_count": "%UPSTREAM_REQUEST_ATTEMPT_COUNT%",
        "partner_id": "%REQ(PARTNER-ID)%",
        "payment_methods": "%REQ(PAYMENT-METHODS)%",
        "upstream_header_bytes_sent": "%UPSTREAM_HEADER_BYTES_SENT%",
        "upstream_header_bytes_received": "%UPSTREAM_HEADER_BYTES_RECEIVED%",
        "request_headers_bytes": "%REQUEST_HEADERS_BYTES%",
        "response_headers_bytes": "%RESPONSE_HEADERS_BYTES%",
        "downstream_header_bytes_received": "%DOWNSTREAM_HEADER_BYTES_RECEIVED%"
      }
    dnsRefreshRate: 240s
    defaultConfig:
      tracingServiceName: APP_LABEL_AND_NAMESPACE
      terminationDrainDuration: 10s
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        BOOTSTRAP_XDS_AGENT: "true"
    discoverySelectors:
      - matchExpressions:
          - key: istio-discovery
            operator: NotIn
            values:
              - disabled
  values:
    global:
      proxy:
        resources:
          requests:
            memory: 128Mi
            cpu: 32m
          limits:
            memory: 512Mi
