apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: istio-mtls-test.zufardhiyaulhaq.com
  namespace: istio-system
spec:
  endpoints:
  - dnsName: istio-mtls-test.zufardhiyaulhaq.com
    recordType: A
    recordTTL: 300
    targets:
    - 43.134.68.205
