name: home-lab-kubernetes-01:pull-request

on:
  pull_request:
    paths:
      - 'clusters/home-lab-kubernetes-01/**'
  
env:
  KUBECONFIG: /tmp/config

jobs:
  kustomize-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: x64
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "scripts/requirements.txt"
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.36.3'
      - name: Install kubectl-slice
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          tag: v1.2.4
          repo: patrickdappollonio/kubectl-slice
          platform: linux
          arch: x86_64
      - name: Setup kustomize
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '5.8.1'
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.8.0
        with:
          helmfile-version: "v1.7.4"
          install-helm: no
          install-helm-plugins: no
          install-kubectl: no
      - name: Setup helm
        uses: azure/setup-helm@v4
        with:
          version: 'v4.2.4'
      - name: Setup helm diff plugin
        run: |
          helm plugin install https://github.com/databus23/helm-diff
      - name: Setup Istioctl
        uses: zufardhiyaulhaq/setup-istioctl@v1.0.0
        with:
          version: 1.30.4
      - name: Setup kubeconfig
        run: |
          echo "$HOME_LAB_KUBERNETES_CONFIG" | base64 -d > $KUBECONFIG
        shell: bash
        env:
          HOME_LAB_KUBERNETES_CONFIG: ${{ secrets.HOME_LAB_KUBERNETES_CONFIG }}
      - name: Diff applications
        run: |
          python3 scripts/deployer.py kustomize diff --cluster-name home-lab-kubernetes-01
  helm-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: x64
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "scripts/requirements.txt"
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.36.3'
      - name: Install kubectl-slice
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          tag: v1.2.4
          repo: patrickdappollonio/kubectl-slice
          platform: linux
          arch: x86_64
      - name: Setup kustomize
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '5.8.1'
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.8.0
        with:
          helmfile-version: "v1.7.4"
          install-helm: no
          install-helm-plugins: no
          install-kubectl: no
      - name: Setup helm
        uses: azure/setup-helm@v4
        with:
          version: 'v4.2.4'
      - name: Setup helm diff plugin
        run: |
          helm plugin install https://github.com/databus23/helm-diff
      - name: Setup Istioctl
        uses: zufardhiyaulhaq/setup-istioctl@v1.0.0
        with:
          version: 1.30.4
      - name: Setup kubeconfig
        run: |
          echo "$HOME_LAB_KUBERNETES_CONFIG" | base64 -d > $KUBECONFIG
        shell: bash
        env:
          HOME_LAB_KUBERNETES_CONFIG: ${{ secrets.HOME_LAB_KUBERNETES_CONFIG }}
      - name: Diff applications
        run: |
          python3 scripts/deployer.py helm diff --cluster-name home-lab-kubernetes-01
  manifests-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: x64
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "scripts/requirements.txt"
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.36.3'
      - name: Install kubectl-slice
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          tag: v1.2.4
          repo: patrickdappollonio/kubectl-slice
          platform: linux
          arch: x86_64
      - name: Setup kustomize
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '5.8.1'
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.8.0
        with:
          helmfile-version: "v1.7.4"
          install-helm: no
          install-helm-plugins: no
          install-kubectl: no
      - name: Setup helm
        uses: azure/setup-helm@v4
        with:
          version: 'v4.2.4'
      - name: Setup helm diff plugin
        run: |
          helm plugin install https://github.com/databus23/helm-diff
      - name: Setup Istioctl
        uses: zufardhiyaulhaq/setup-istioctl@v1.0.0
        with:
          version: 1.30.4
      - name: Setup kubeconfig
        run: |
          echo "$HOME_LAB_KUBERNETES_CONFIG" | base64 -d > $KUBECONFIG
        shell: bash
        env:
          HOME_LAB_KUBERNETES_CONFIG: ${{ secrets.HOME_LAB_KUBERNETES_CONFIG }}
      - name: Diff applications
        run: |
          python3 scripts/deployer.py manifests diff --cluster-name home-lab-kubernetes-01
  istio-control-plane-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: x64
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "scripts/requirements.txt"
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.36.3'
      - name: Install kubectl-slice
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          tag: v1.2.4
          repo: patrickdappollonio/kubectl-slice
          platform: linux
          arch: x86_64
      - name: Setup kustomize
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '5.8.1'
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.8.0
        with:
          helmfile-version: "v1.7.4"
          install-helm: no
          install-helm-plugins: no
          install-kubectl: no
      - name: Setup helm
        uses: azure/setup-helm@v4
        with:
          version: 'v4.2.4'
      - name: Setup helm diff plugin
        run: |
          helm plugin install https://github.com/databus23/helm-diff
      - name: Setup Istioctl
        uses: zufardhiyaulhaq/setup-istioctl@v1.0.0
        with:
          version: 1.30.4
      - name: Setup kubeconfig
        run: |
          echo "$HOME_LAB_KUBERNETES_CONFIG" | base64 -d > $KUBECONFIG
        shell: bash
        env:
          HOME_LAB_KUBERNETES_CONFIG: ${{ secrets.HOME_LAB_KUBERNETES_CONFIG }}
      - name: Diff applications
        run: |
          python3 scripts/deployer.py istio control-plane diff --cluster-name home-lab-kubernetes-01 --revision 1-30-4
  istio-gateway-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: x64
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "scripts/requirements.txt"
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.36.3'
      - name: Install kubectl-slice
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          tag: v1.2.4
          repo: patrickdappollonio/kubectl-slice
          platform: linux
          arch: x86_64
      - name: Setup kustomize
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '5.8.1'
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.8.0
        with:
          helmfile-version: "v1.7.4"
          install-helm: no
          install-helm-plugins: no
          install-kubectl: no
      - name: Setup helm
        uses: azure/setup-helm@v4
        with:
          version: 'v4.2.4'
      - name: Setup helm diff plugin
        run: |
          helm plugin install https://github.com/databus23/helm-diff
      - name: Setup Istioctl
        uses: zufardhiyaulhaq/setup-istioctl@v1.0.0
        with:
          version: 1.30.4
      - name: Setup kubeconfig
        run: |
          echo "$HOME_LAB_KUBERNETES_CONFIG" | base64 -d > $KUBECONFIG
        shell: bash
        env:
          HOME_LAB_KUBERNETES_CONFIG: ${{ secrets.HOME_LAB_KUBERNETES_CONFIG }}
      - name: Diff applications
        run: |
          python3 scripts/deployer.py istio gateway diff --cluster-name home-lab-kubernetes-01 --revision 1-30-4

  kustomize-dryrun:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: x64
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "scripts/requirements.txt"
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.36.3'
      - name: Install kubectl-slice
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          tag: v1.2.4
          repo: patrickdappollonio/kubectl-slice
          platform: linux
          arch: x86_64
      - name: Setup kustomize
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '5.8.1'
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.8.0
        with:
          helmfile-version: "v1.7.4"
          install-helm: no
          install-helm-plugins: no
          install-kubectl: no
      - name: Setup helm
        uses: azure/setup-helm@v4
        with:
          version: 'v4.2.4'
      - name: Setup helm diff plugin
        run: |
          helm plugin install https://github.com/databus23/helm-diff
      - name: Setup Istioctl
        uses: zufardhiyaulhaq/setup-istioctl@v1.0.0
        with:
          version: 1.30.4
      - name: Setup kubeconfig
        run: |
          echo "$HOME_LAB_KUBERNETES_CONFIG" | base64 -d > $KUBECONFIG
        shell: bash
        env:
          HOME_LAB_KUBERNETES_CONFIG: ${{ secrets.HOME_LAB_KUBERNETES_CONFIG }}
      - name: dryrun applications
        run: |
          python3 scripts/deployer.py kustomize dryrun --cluster-name home-lab-kubernetes-01
  helm-dryrun:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: x64
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "scripts/requirements.txt"
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.36.3'
      - name: Install kubectl-slice
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          tag: v1.2.4
          repo: patrickdappollonio/kubectl-slice
          platform: linux
          arch: x86_64
      - name: Setup kustomize
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '5.8.1'
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.8.0
        with:
          helmfile-version: "v1.7.4"
          install-helm: no
          install-helm-plugins: no
          install-kubectl: no
      - name: Setup helm
        uses: azure/setup-helm@v4
        with:
          version: 'v4.2.4'
      - name: Setup helm diff plugin
        run: |
          helm plugin install https://github.com/databus23/helm-diff
      - name: Setup Istioctl
        uses: zufardhiyaulhaq/setup-istioctl@v1.0.0
        with:
          version: 1.30.4
      - name: Setup kubeconfig
        run: |
          echo "$HOME_LAB_KUBERNETES_CONFIG" | base64 -d > $KUBECONFIG
        shell: bash
        env:
          HOME_LAB_KUBERNETES_CONFIG: ${{ secrets.HOME_LAB_KUBERNETES_CONFIG }}
      - name: dryrun applications
        run: |
          python3 scripts/deployer.py helm dryrun --cluster-name home-lab-kubernetes-01
  manifests-dryrun:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: x64
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "scripts/requirements.txt"
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.36.3'
      - name: Install kubectl-slice
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          tag: v1.2.4
          repo: patrickdappollonio/kubectl-slice
          platform: linux
          arch: x86_64
      - name: Setup kustomize
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '5.8.1'
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.8.0
        with:
          helmfile-version: "v1.7.4"
          install-helm: no
          install-helm-plugins: no
          install-kubectl: no
      - name: Setup helm
        uses: azure/setup-helm@v4
        with:
          version: 'v4.2.4'
      - name: Setup helm diff plugin
        run: |
          helm plugin install https://github.com/databus23/helm-diff
      - name: Setup Istioctl
        uses: zufardhiyaulhaq/setup-istioctl@v1.0.0
        with:
          version: 1.30.4
      - name: Setup kubeconfig
        run: |
          echo "$HOME_LAB_KUBERNETES_CONFIG" | base64 -d > $KUBECONFIG
        shell: bash
        env:
          HOME_LAB_KUBERNETES_CONFIG: ${{ secrets.HOME_LAB_KUBERNETES_CONFIG }}
      - name: dryrun applications
        run: |
          python3 scripts/deployer.py manifests dryrun --cluster-name home-lab-kubernetes-01
  istio-control-plane-dryrun:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: x64
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "scripts/requirements.txt"
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.36.3'
      - name: Install kubectl-slice
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          tag: v1.2.4
          repo: patrickdappollonio/kubectl-slice
          platform: linux
          arch: x86_64
      - name: Setup kustomize
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '5.8.1'
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.8.0
        with:
          helmfile-version: "v1.7.4"
          install-helm: no
          install-helm-plugins: no
          install-kubectl: no
      - name: Setup helm
        uses: azure/setup-helm@v4
        with:
          version: 'v4.2.4'
      - name: Setup helm diff plugin
        run: |
          helm plugin install https://github.com/databus23/helm-diff
      - name: Setup Istioctl
        uses: zufardhiyaulhaq/setup-istioctl@v1.0.0
        with:
          version: 1.30.4
      - name: Setup kubeconfig
        run: |
          echo "$HOME_LAB_KUBERNETES_CONFIG" | base64 -d > $KUBECONFIG
        shell: bash
        env:
          HOME_LAB_KUBERNETES_CONFIG: ${{ secrets.HOME_LAB_KUBERNETES_CONFIG }}
      - name: dryrun applications
        run: |
          python3 scripts/deployer.py istio control-plane dryrun --cluster-name home-lab-kubernetes-01 --revision 1-30-4
  istio-gateway-dryrun:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: x64
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "scripts/requirements.txt"
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.36.3'
      - name: Install kubectl-slice
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          tag: v1.2.4
          repo: patrickdappollonio/kubectl-slice
          platform: linux
          arch: x86_64
      - name: Setup kustomize
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '5.8.1'
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.8.0
        with:
          helmfile-version: "v1.7.4"
          install-helm: no
          install-helm-plugins: no
          install-kubectl: no
      - name: Setup helm
        uses: azure/setup-helm@v4
        with:
          version: 'v4.2.4'
      - name: Setup helm diff plugin
        run: |
          helm plugin install https://github.com/databus23/helm-diff
      - name: Setup Istioctl
        uses: zufardhiyaulhaq/setup-istioctl@v1.0.0
        with:
          version: 1.30.4
      - name: Setup kubeconfig
        run: |
          echo "$HOME_LAB_KUBERNETES_CONFIG" | base64 -d > $KUBECONFIG
        shell: bash
        env:
          HOME_LAB_KUBERNETES_CONFIG: ${{ secrets.HOME_LAB_KUBERNETES_CONFIG }}
      - name: dryrun applications
        run: |
          python3 scripts/deployer.py istio gateway dryrun --cluster-name home-lab-kubernetes-01 --revision 1-30-4
